name: Assign New Issues

on:
  issues:
    types:
      - opened

jobs:
  assign_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Assign issue to team member
        uses: actions-ecosystem/action-add-issue-assigner@v1
        with:
          assignees: 'KieranMcHugh' # Replace with the GitHub username of the team member
          github_token: ${{ secrets.GITHUB_TOKEN }}
