name: Assign New Issues

on:
  issues:
    types:
      - opened

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      # .take in an issue comment. 
      - name: take an issue
        uses: KieranMcHugh/take-action@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
