nname: Assign to team member
on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  label-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign to KieranMcHugh
        uses: actions-ecosystem/action-add-issue-assigner@v1
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            assignees: 'KieranMcHugh'
