name: Issue Assignment
on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: "Auto-assign issue"
        uses: actions/github-script@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: KieranMcHugh
