name: Assign Issue

on: 
  issues: 
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: 'user/assign-issue-action@v1' 
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
        with:
          issue_number: ${{ github.event.issue.number }}
          assignee: 'KieranMcHugh' 
