name: Assign New Issues

on:
  issues:
    types:
      - opened

jobs:
  assign_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Assign issue to a specific team member
        uses: actions/github-script@v6
        with:
          script: |
            const assignee = 'KieranMcHugh';
            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [assignee]
            });
