name: Issue Assignment


on:
  issues:
    types: [opened]
    
permissions:
  issues: write
  
jobs:
  add_assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Assign new issues to a specific user
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: "KieranMcHugh" # Replace X with the GitHub username of the team member
